spring.application.name=api-gateway

server.port=8082
spring.config.import=optional:configserver:
eureka.client.service-url.defaultZone=http://service-discovery:8081/eureka/


# ---- ROTAS ----
# Rota para Auth Service - Registro
spring.cloud.gateway.routes[0].id=auth-service-register
spring.cloud.gateway.routes[0].uri=lb://auth-service
spring.cloud.gateway.routes[0].predicates[0]=Path=/api/auth/register
spring.cloud.gateway.routes[0].filters[0]=StripPrefix=2

# Rota para Auth Service - Login
spring.cloud.gateway.routes[1].id=auth-service-login
spring.cloud.gateway.routes[1].uri=lb://auth-service
spring.cloud.gateway.routes[1].predicates[0]=Path=/api/auth/login
spring.cloud.gateway.routes[1].filters[0]=StripPrefix=2

# Rota para Auth Service - Refresh Token
spring.cloud.gateway.routes[2].id=auth-service-refresh
spring.cloud.gateway.routes[2].uri=lb://auth-service
spring.cloud.gateway.routes[2].predicates[0]=Path=/api/auth/refresh
spring.cloud.gateway.routes[2].filters[0]=StripPrefix=2

# ----- CORS -----
spring.cloud.gateway.globalcors.cors-configurations.[/**].allowed-origins=*
spring.cloud.gateway.globalcors.cors-configurations.[/**].allowed-methods=GET,POST,PUT,DELETE,OPTIONS
spring.cloud.gateway.globalcors.cors-configurations.[/**].allowed-headers=*
spring.cloud.gateway.globalcors.cors-configurations.[/**].allow-credentials=true

# ===== ACTUATOR =====
management.endpoints.web.exposure.include=health,info,gateway
management.endpoint.health.show-details=always