FROM maven:3.9.9-eclipse-temurin-21 as build
WORKDIR /app

COPY ./pom.xml .

COPY src ./src
RUN mvn clean package -DskipTests -B

FROM alpine/java:21-jre
WORKDIR /app
COPY --from=build /app/target/*.jar app.jar
EXPOSE 8086
ENTRYPOINT ["java", "-jar", "app.jar"]

