spring.application.name=ranking-service
server.port=8086

spring.config.import=optional:configserver:

# ===== CONFIGURAÇÕES DO EUREKA =====
eureka.client.service-url.defaultZone=http://${EUREKA_HOST:localhost}:${EUREKA_PORT:8081}/eureka/
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true
eureka.instance.prefer-ip-address=true
eureka.instance.hostname=${spring.application.name}