# ===== CONFIGURAÇÕES DO SERVIDOR =====
server.port=8084

# ===== CONFIGURAÇÕES DA APLICAÇÃO =====
spring.application.name=matchmaking-service
spring.config.import=optional:configserver:

# ===== CONFIGURAÇÕES DO BANCO DE DADOS =====
spring.data.mongodb.host=db-matchmaking
spring.data.mongodb.database=match-db
spring.data.mongodb.port=27017
spring.data.mongodb.username=ttplatform
spring.data.mongodb.password=ttplatform123
# ===== CONFIGURAÇÕES DO JPA/HIBERNATE =====
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.show-sql=false
spring.jpa.open-in-view=false

# ===== CONFIGURAÇÕES DO EUREKA =====
eureka.client.service-url.defaultZone=http://${EUREKA_HOST:localhost}:${EUREKA_PORT:8081}/eureka/
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true
eureka.instance.prefer-ip-address=true
eureka.instance.hostname=${spring.application.name}

# ===== CONFIGURAÇÕES DO ACTUATOR =====
management.endpoints.web.exposure.include=health,info,metrics
management.endpoint.health.show-details=always

# ========= URL DOS CLIENTS =======
feign.auth-service.url=http://auth-service:8083