apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-discovery-deployment
  labels:
    app: service-discovery
spec:
  replicas: 1
  selector:
    matchLabels:
      app: service-discovery
  template:
    metadata:
      labels:
        app: service-discovery
    spec:
      containers:
        - name: ttplatform-service-discovery
          image: table-tennis-platform-service-discovery:latest
          imagePullPolicy: IfNotPresent
      restartPolicy: Always
