input {
  tcp {
    port => 5000
    codec => json_lines
  }
}

filter {
  # Nenhum filtro é necessário se o log já vem em JSON do Spring Boot
}

output {
  elasticsearch {
    hosts => ["http://elasticsearch:9200"]
    index => "microservices-logs-%{+YYYY.MM.dd}"
  }
  stdout { codec => rubydebug } # Útil para debug no console do Logstash
}